# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TVSeriesApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MusicApp
  pod 'Alamofire', '~> 5.2'

  target 'TVSeriesAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TVSeriesAppUITests' do
    # Pods for testing
  end

end